name: update

on:
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@15c23237552697eacac7b32ef9f217906db85db3 # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      php: 8.5
      extensions: mbstring
      git-name: kawax
      git-email: 1502086+kawax@users.noreply.github.com
  npm:
    uses: kawax/npm-workflow/.github/workflows/update.yml@0340b8e7582f60e440c100abca8c306ddf221fda # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      git-name: kawax
      git-email: 1502086+kawax@users.noreply.github.com
